### ISSUE TITLE
Are the plate, pouring, and catching scenes included?

### ISSUE THREAD

**Issue by DanielTakeshi** [cschenck/SmoothParticleNets#2]
Hi @cschenck,

Thank you very much for putting the code for SPNets here.

From reading the paper https://arxiv.org/pdf/1806.06094.pdf  it looks like there are 4 scenes that you used for testing: ladle, plate, pouring, and catching. Are these scenes available to test from the code in this repository? I searched throughout the repository but I didn't see anything that seems to implement those scenes. If these are not available, do you have any recommendations on how I might be able to get started with implementing such scenes?

**Comment by cschenck** [comment]
They are not in this repository. However, I can give you the relevant pieces you need to implement them. [Here's a link](https://storage.googleapis.com/www.connorschenck.com/models.zip) to all the model files and [here's a link](https://storage.googleapis.com/www.connorschenck.com/scene_initializers.py) to the python code that sets up the scenes. You may note that there are more than 4 scenes in this file; I toyed around with a lot of different setups, but only went with those 4 in the paper.

Unfortunately, you won't be able to run that code. I was an intern at Nvidia at the time when I was working on it, and I modified the internals of Nvidia Flex for this project as well as made pybindings for it, which is what I used to run the simulation. I am legally not allowed to release that version of Flex, but the code should hopefully be enough to allow you to implement it on your own.

**Comment by DanielTakeshi** [comment]
Hi @cschenck 

Thank you very much for the response! 
We fully understand issues with Flex + releasing code. I will take a look at the models and code and see what I can figure out from there (particularly the ladle).
